#!/bin/bash
set -eu -o pipefail

die() {
    if [ $# -eq 0 ]; then cat; else echo "$@"; fi
    exit 1
}

usage() {
    die <<USAGE
Usage:
  make-release [-n] <tag>
USAGE
}

dry_run=false
while [ "$#" -gt 1 ]; do
    case "$1" in
        -n) dry_run=true;;
        *) usage;;
    esac
    shift
done
if [ $# != 1 ]; then usage; fi

maybe() {
    if $dry_run; then echo "$@"; else "$@"; fi
}

tagname="$1"
if ! [[ $tagname =~ ^[0-9]+(\.[0-9]+){2}(_rc[0-9]+)?$ ]]; then
    die <<EOF
$tagname must match the form <int>.<int>.<int>[_rc<int>]
EOF
fi

branch=$(git symbolic-ref --short -q HEAD)
if [ "$branch" != master ]; then
    die "You should be on master to make a release."
fi

package="erl_optics"

maybe git pull
maybe git checkout -b "release/${tagname}"
maybe sed -ri "s_vsn, \".*\"_vsn, \"${tagname}\"_" ./src/$package.app.src
maybe git add ./src/$package.app.src
maybe git commit -m "Bump version to ${tagname}"
maybe git tag -a "${tagname}"
maybe git push origin "release/${tagname}" "${tagname}"
maybe git checkout master

echo "PR: https://github.com/rkallos/erl-optics/compare/release/${tagname}"
