-define(APP, erl_optics).
-define(ENV(Key, Default), application:get_env(?APP, Key, Default)).
-define(ENV_HOSTNAME, localhost).
-define(ENV_PORT, 2003).
-define(DEFAULT_PORT, 1055).
-define(DEFAULT_INTERVAL, 10000).
